name: build

on:
  push:
    branches:
    - main
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Setup node 12
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458 # renovate: tag=v2
      with:
        node-version: '12'


    - name: node_modules cache
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2
      with:
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json', '*.lock') }}
        path: |
          node_modules


    - name: Install dependencies
      run: |
        yarn install

    - name: Build
      run: |
        npm run build


    - name: Run current action
      id: current
      uses: ./
      with:
        group: org.ow2.asm
        name: asm
        min: 5, 6.0
        max: 7.0.999
        exclude: 7.1

    - name: Validate current action
      env:
        OUTPUT: ${{ steps.current.outputs.stable }}
      run: |
        if [ "${{ contains(fromJSON(env.OUTPUT), '6.1.1') }}" == "true" ]; then
          echo "Valid"
        else
          echo "::error Current action output doesn't contain '6.1.1': $OUTPUT"
          exit 1
        fi
        if [ "${{ contains(fromJSON(env.OUTPUT), '5.1') }}" != "false" ]; then
          echo "::error Current action output contains '5.1': $OUTPUT"
          exit 1
        fi
        if [ "${{ contains(fromJSON(env.OUTPUT), '8.0') }}" != "false" ]; then
          echo "::error Current action output contains '8.0': $OUTPUT"
          exit 1
        fi
        if [ "${{ contains(fromJSON(env.OUTPUT), '7.1') }}" != "false" ]; then
          echo "::error Current action output contains '7.1': $OUTPUT"
          exit 1
        fi


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && env.PUSH_BACK_TOKEN }}
      uses: remal-github-actions/push-back@66904157f8f1739e4baf4fb75ffdd8b1c1b6b78f # renovate: tag=v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        message: '[push-back] Push-back updated files during build'


    - name: Read version
      id: readVersion
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: remal-github-actions/read-nodejs-package-version@5d25d3299980c9e01ba835768ae469b66d98d578 # renovate: tag=v1

    - name: Create tag
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.PUSH_BACK_TOKEN }}
      uses: remal-github-actions/create-tag@b97081c68f4f01187bf6a170a557fb92a68a7592 # renovate: tag=v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        tagName: 'v${{ steps.readVersion.outputs.majorVersion }}'
        forcePush: 'true'
